### ISSUE TITLE
Regarding the implementation of ERGO-12

### ISSUE THREAD

**Issue by Vayne0227** [uzh-rpg/event_representation_study#3]
Hello, I'd like to inquire about the implementation details of your event representation model, ERGO-12. I have attempted to run it on the mini n-imagenet dataset, but unfortunately, I haven't achieved the desired accuracy. Here are the implementation details I used. Could you please assist me and provide some guidance on this matter? Thank you.
![14eb1b029b10f7f9511f159f1d0c21c](https://github.com/uzh-rpg/event_representation_study/assets/66624169/9d3863ff-551f-4fb7-b0d1-5bc723165390)

**Comment by NikolaZubic** [comment]
Hi @Vayne0227 ,
You are only using one channel which is not ERGO-12. You need 11 more 😃 Also, that is not the first channel.

**Comment by Vayne0227** [comment]
Thank you so much for your assistance, author. I misunderstood the meaning before. I appreciate your help.
