### ISSUE TITLE
Problems Downloading Weights and Datasets

### ISSUE THREAD

**Issue by silvada95** [uzh-rpg/event_representation_study#5]
Hi,

I am trying to download the weights and preprocessed datasets, but I am not getting any response from the sites. Is it possible to check if everything is ok with them? Otherwise, I will need to ensure that this is not a connectivity issue on my end.

**Comment by NikolaZubic** [comment]
@silvada95 I am not having any problems and can download fine. I guess it's a connectivity issue on your side.
